name: Build and Deploy Web Game

on:
  push:
    branches: [main]

jobs:
  export-html5:
    name: Export HTML5 and Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up build version
        run: bash ${GITHUB_WORKSPACE}/generate_build_version.sh

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.4.1
          use-dotnet: false

      - name: Download export templates
        run: |
            mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
            wget https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz -O templates.tpz
            unzip templates.tpz -d extracted_templates
            cp extracted_templates/templates/web/*.zip ~/.local/share/godot/export_templates/4.4.1.stable/



      - name: Export HTML5
        run: |
          godot --headless --export-release "Web" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
